version: '3'

volumes:
  db-data:
  php-fpm-socket:

services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
      - php-fpm-socket:/var/run/php-fpm
    restart: always
    depends_on:
      - app
  app:
    container_name: app
    build: ./docker/app
    environment:
      LOG_CHANNEL: stderr
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-postgres}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - ./backend:/var/www/html
      - php-fpm-socket:/var/run/php-fpm
    restart: always
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:alpine
    environment: 
      TZ: ${TZ:-Asia/Tokyo}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    restart: always
    ports:
      - ${DB_PORT:-5432}:5432
    volumes: 
      - db-data:/var/lib/postgresql/data
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT:-8080}:8080
