version: '3.9'

volumes:
  db-data:
  # php-fpm-socket:

services:
  web:
    container_name: web
    # build: ./docker/web 
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    restart: always
    depends_on:
      - app
  app:
    container_name: app
    build: ./docker/app
    environment:
      LOG_CHANNEL: stderr
      DB_CONNECTION: "pgsql"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_DATABASE: "laravel"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
    restart: always
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:alpine
    environment: 
      TZ: "Asia/Tokyo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "laravel"
    volumes: 
      - db-data:/var/lib/postgresql/data
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
